window.Tandem                 = require('tandem-core')
window.Tandem.Client          = require('./src/client/tandem')
window.Tandem.Engine          = require('./src/client/engine')
window.Tandem.File            = require('./src/client/file')
window.Tandem.NetworkAdapter  = require('./src/client/network')
